/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package drrm;

import dao.ARFDao;
import dao.ConnectionProvider;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import model.ARFModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author harsh
 */
public class AssignResponseForce extends javax.swing.JFrame {

    /**
     * Creates new form AssignResponseForce
     */
    public AssignResponseForce() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AssRespLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DisTable = new javax.swing.JTable();
        StateDisCom = new javax.swing.JLabel();
        StateDisComField = new javax.swing.JTextField();
        CidAssLabel = new javax.swing.JLabel();
        CompStateAssLabel = new javax.swing.JLabel();
        DisComAssLabel = new javax.swing.JLabel();
        TFHAssLabel = new javax.swing.JLabel();
        ContactAssLabel = new javax.swing.JLabel();
        TimingsAssLabel = new javax.swing.JLabel();
        CidAssField = new javax.swing.JTextField();
        CompStateField = new javax.swing.JTextField();
        TFHAssField = new javax.swing.JTextField();
        DisComComboBox = new javax.swing.JComboBox<>();
        ContactAssField = new javax.swing.JTextField();
        TimingsAssField = new javax.swing.JTextField();
        AssBtn = new javax.swing.JButton();
        EnterArfBtn = new javax.swing.JButton();
        BackAssBtn = new javax.swing.JButton();
        AssRespForLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AssRespLabel.setFont(new java.awt.Font("Century Gothic", 1, 58)); // NOI18N
        AssRespLabel.setForeground(new java.awt.Color(255, 255, 255));
        AssRespLabel.setText("Assigning Response Force");
        getContentPane().add(AssRespLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 49, -1, -1));

        DisTable.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        DisTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Disaster", "Disaster Committee"
            }
        ));
        DisTable.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                DisTableComponentResized(evt);
            }
        });
        jScrollPane1.setViewportView(DisTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 350, -1, -1));

        StateDisCom.setFont(new java.awt.Font("Georgia", 1, 32)); // NOI18N
        StateDisCom.setForeground(new java.awt.Color(255, 255, 255));
        StateDisCom.setText("State");
        getContentPane().add(StateDisCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 230, -1, -1));

        StateDisComField.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        StateDisComField.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(StateDisComField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1570, 230, 251, -1));

        CidAssLabel.setFont(new java.awt.Font("Georgia", 1, 32)); // NOI18N
        CidAssLabel.setForeground(new java.awt.Color(255, 255, 255));
        CidAssLabel.setText("CID");
        getContentPane().add(CidAssLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 327, -1));

        CompStateAssLabel.setFont(new java.awt.Font("Georgia", 1, 32)); // NOI18N
        CompStateAssLabel.setForeground(new java.awt.Color(255, 255, 255));
        CompStateAssLabel.setText("Complaint State");
        getContentPane().add(CompStateAssLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 364, 327, -1));

        DisComAssLabel.setFont(new java.awt.Font("Georgia", 1, 32)); // NOI18N
        DisComAssLabel.setForeground(new java.awt.Color(255, 255, 255));
        DisComAssLabel.setText("Disaster Committee");
        getContentPane().add(DisComAssLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 456, -1, -1));

        TFHAssLabel.setFont(new java.awt.Font("Georgia", 1, 32)); // NOI18N
        TFHAssLabel.setForeground(new java.awt.Color(255, 255, 255));
        TFHAssLabel.setText("Task Force Head");
        getContentPane().add(TFHAssLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 559, 327, -1));

        ContactAssLabel.setFont(new java.awt.Font("Georgia", 1, 32)); // NOI18N
        ContactAssLabel.setForeground(new java.awt.Color(255, 255, 255));
        ContactAssLabel.setText("Contact");
        getContentPane().add(ContactAssLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 659, 327, -1));

        TimingsAssLabel.setFont(new java.awt.Font("Georgia", 1, 32)); // NOI18N
        TimingsAssLabel.setForeground(new java.awt.Color(255, 255, 255));
        TimingsAssLabel.setText("Timings");
        getContentPane().add(TimingsAssLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 752, 327, -1));

        CidAssField.setFont(new java.awt.Font("Georgia", 1, 32)); // NOI18N
        CidAssField.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(CidAssField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 255, 490, -1));

        CompStateField.setFont(new java.awt.Font("Georgia", 1, 32)); // NOI18N
        CompStateField.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(CompStateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 359, 490, -1));

        TFHAssField.setFont(new java.awt.Font("Georgia", 1, 32)); // NOI18N
        TFHAssField.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(TFHAssField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 554, 490, -1));

        DisComComboBox.setFont(new java.awt.Font("Georgia", 1, 32)); // NOI18N
        DisComComboBox.setForeground(new java.awt.Color(0, 51, 102));
        DisComComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F Task Force", "E Task Force", "T Task Force", "D Task Force", "L Task Force", "C Task Force", "S Task Force", "V Task Force", "W Task Force" }));
        getContentPane().add(DisComComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 456, 490, -1));

        ContactAssField.setFont(new java.awt.Font("Georgia", 1, 32)); // NOI18N
        ContactAssField.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(ContactAssField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 649, 490, -1));

        TimingsAssField.setFont(new java.awt.Font("Georgia", 1, 32)); // NOI18N
        TimingsAssField.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(TimingsAssField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 747, 490, -1));

        AssBtn.setFont(new java.awt.Font("Georgia", 1, 32)); // NOI18N
        AssBtn.setForeground(new java.awt.Color(0, 51, 102));
        AssBtn.setText("ASSIGN");
        AssBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssBtnActionPerformed(evt);
            }
        });
        getContentPane().add(AssBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 910, -1, -1));

        EnterArfBtn.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        EnterArfBtn.setForeground(new java.awt.Color(0, 51, 102));
        EnterArfBtn.setText("Enter");
        EnterArfBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterArfBtnActionPerformed(evt);
            }
        });
        getContentPane().add(EnterArfBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 290, -1, -1));

        BackAssBtn.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        BackAssBtn.setForeground(new java.awt.Color(0, 51, 102));
        BackAssBtn.setText("Back");
        BackAssBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackAssBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackAssBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1680, 100, -1, -1));

        AssRespForLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Assign Response Force.png"))); // NOI18N
        AssRespForLabel.setText("Label");
        getContentPane().add(AssRespForLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterArfBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterArfBtnActionPerformed
        // TODO add your handling code here:
        String state=StateDisComField.getText();
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st =  con.createStatement();
            ResultSet rs=st.executeQuery("select DisasterName,DisasterCommittee from discom where state='"+state+"';");
            DisTable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"No state exists!");
            setVisible(false);
        }
    }//GEN-LAST:event_EnterArfBtnActionPerformed

    private void DisTableComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_DisTableComponentResized
        // TODO add your handling code here:
        DisTable.setRowHeight(40);
        DisTable.setShowGrid(true);
    }//GEN-LAST:event_DisTableComponentResized

    private void AssBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssBtnActionPerformed
        // TODO add your handling code here:
        //String query1 = "insert into action(Cid,ComplaintState,DisasterCommittee,TaskForceHead,Contact,Timings) values('"+reg.getcid()+"','"+reg.getcomplaintstate()+"','"+reg.getdiscommitte()+"','"+reg.gettaskforcehead()+"','"+reg.getcontact()+"','"+reg.gettimings()+"');
	//DbOperations.setDataorDelete(query1,"ResponseForce assigned Successfully!!");
        try{
            ARFModel reg =new ARFModel();
            reg.setCid(CidAssField.getText());
            reg.setComplaintstate(CompStateField.getText());
            reg.setDiscommittee(DisComComboBox.getSelectedItem().toString());
            reg.setTaskforcehead(TFHAssField.getText());
            reg.setContact(ContactAssField.getText());
            reg.setTimings(TimingsAssField.getText());
            
            ARFDao.assign(reg);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Enter all fields");
            setVisible(false);
        }
    }//GEN-LAST:event_AssBtnActionPerformed

    private void BackAssBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackAssBtnActionPerformed
        // TODO add your handling code here:
        this.toBack();
	ViewComplaintDetails newFrame2 = new ViewComplaintDetails();
	newFrame2.setVisible(true);
	newFrame2.toFront();
    }//GEN-LAST:event_BackAssBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignResponseForce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignResponseForce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignResponseForce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignResponseForce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignResponseForce().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssBtn;
    private javax.swing.JLabel AssRespForLabel;
    private javax.swing.JLabel AssRespLabel;
    private javax.swing.JButton BackAssBtn;
    private javax.swing.JTextField CidAssField;
    private javax.swing.JLabel CidAssLabel;
    private javax.swing.JLabel CompStateAssLabel;
    private javax.swing.JTextField CompStateField;
    private javax.swing.JTextField ContactAssField;
    private javax.swing.JLabel ContactAssLabel;
    private javax.swing.JLabel DisComAssLabel;
    private javax.swing.JComboBox<String> DisComComboBox;
    private javax.swing.JTable DisTable;
    private javax.swing.JButton EnterArfBtn;
    private javax.swing.JLabel StateDisCom;
    private javax.swing.JTextField StateDisComField;
    private javax.swing.JTextField TFHAssField;
    private javax.swing.JLabel TFHAssLabel;
    private javax.swing.JTextField TimingsAssField;
    private javax.swing.JLabel TimingsAssLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
