/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package drrm;

import dao.ConnectionProvider;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author harsh
 */
public class CheckStatus extends javax.swing.JFrame {

    /**
     * Creates new form CheckStatus
     */
    public CheckStatus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComplaintIdLabel = new javax.swing.JLabel();
        SubmitBtn1 = new javax.swing.JButton();
        ComplaintIdField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ActionTableView = new javax.swing.JTable();
        BackBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ComplaintIdLabel.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        ComplaintIdLabel.setForeground(new java.awt.Color(255, 255, 255));
        ComplaintIdLabel.setText("Complaint Id");
        getContentPane().add(ComplaintIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, -1, -1));

        SubmitBtn1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        SubmitBtn1.setForeground(new java.awt.Color(0, 51, 102));
        SubmitBtn1.setText("SUBMIT");
        SubmitBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(SubmitBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 470, -1, -1));

        ComplaintIdField.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        ComplaintIdField.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(ComplaintIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 380, 297, -1));

        ActionTableView.setFont(new java.awt.Font("Georgia", 1, 22)); // NOI18N
        ActionTableView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Task Force Head", "Contact", "Timings", "Disaster Committee"
            }
        ));
        ActionTableView.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                ActionTableViewComponentResized(evt);
            }
        });
        jScrollPane1.setViewportView(ActionTableView);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 590, 1740, 370));

        BackBtn.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        BackBtn.setForeground(new java.awt.Color(0, 51, 102));
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1710, 60, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Check Complaint Status.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        this.toBack();
	MainPage newFrame1 = new MainPage();
	newFrame1.setVisible(true);
	newFrame1.toFront();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void SubmitBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtn1ActionPerformed
        // TODO add your handling code here:
        String complaintid=ComplaintIdField.getText();
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st =  con.createStatement();
            ResultSet rs=st.executeQuery("select TaskForceHead,Contact,Timings,DisasterCommittee from action where cid='"+complaintid+"';");
            ActionTableView.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"No record exists!");
            setVisible(false);
        }
    }//GEN-LAST:event_SubmitBtn1ActionPerformed

    private void ActionTableViewComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ActionTableViewComponentResized
        // TODO add your handling code here:
        ActionTableView.setRowHeight(40);
        ActionTableView.setShowGrid(true);
    }//GEN-LAST:event_ActionTableViewComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ActionTableView;
    private javax.swing.JButton BackBtn;
    private javax.swing.JTextField ComplaintIdField;
    private javax.swing.JLabel ComplaintIdLabel;
    private javax.swing.JButton SubmitBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
