/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package drrm;

import dao.ConnectionProvider;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author harsh
 */
public class DisasterProne extends javax.swing.JFrame {

    /**
     * Creates new form DisasterProne
     */
    public DisasterProne() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StateLabel = new javax.swing.JLabel();
        StateField = new javax.swing.JTextField();
        EnterBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DisViewTable = new javax.swing.JTable();
        BackBtn = new javax.swing.JButton();
        DisProne = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StateLabel.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        StateLabel.setForeground(new java.awt.Color(0, 51, 51));
        StateLabel.setText("State");
        getContentPane().add(StateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, -1));

        StateField.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        getContentPane().add(StateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 250, 300, -1));

        EnterBtn.setFont(new java.awt.Font("Georgia", 1, 26)); // NOI18N
        EnterBtn.setText("Enter");
        EnterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterBtnActionPerformed(evt);
            }
        });
        getContentPane().add(EnterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 260, -1, -1));

        DisViewTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DisViewTable.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        DisViewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "State", "Disaster Name", "Places"
            }
        ));
        DisViewTable.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                DisViewTableComponentResized(evt);
            }
        });
        jScrollPane1.setViewportView(DisViewTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 1580, -1));

        BackBtn.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        BackBtn.setForeground(new java.awt.Color(0, 51, 51));
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1690, 80, -1, -1));

        DisProne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Disaster Prone Zones.png"))); // NOI18N
        DisProne.setText("Label");
        getContentPane().add(DisProne, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterBtnActionPerformed
        // TODO add your handling code here:
        String state=StateField.getText();
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st =  con.createStatement();
            ResultSet rs=st.executeQuery("select * from display where state='"+state+"';");
            DisViewTable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"No state exists!");
            setVisible(false);
        }
    }//GEN-LAST:event_EnterBtnActionPerformed

    private void DisViewTableComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_DisViewTableComponentResized
        // TODO add your handling code here:
        DisViewTable.setRowHeight(40);
        DisViewTable.setShowGrid(true);
    }//GEN-LAST:event_DisViewTableComponentResized

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        this.toBack();
	MainPage newFrame1 = new MainPage();
	newFrame1.setVisible(true);
	newFrame1.toFront();
    }//GEN-LAST:event_BackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisasterProne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisasterProne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisasterProne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisasterProne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisasterProne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel DisProne;
    private javax.swing.JTable DisViewTable;
    private javax.swing.JButton EnterBtn;
    private javax.swing.JTextField StateField;
    private javax.swing.JLabel StateLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
