/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package drrm;

import javax.swing.JOptionPane;

/**
 *
 * @author harsh
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }
    public void clear(){
        UsernameField.setText("");
        PwdField.setText("");
        LoginBtn.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UsernameLabel = new javax.swing.JLabel();
        PwdLabel = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        PwdField = new javax.swing.JPasswordField();
        BackBtn = new javax.swing.JButton();
        LoginBtn = new javax.swing.JButton();
        ViewCompDetBtn = new javax.swing.JButton();
        LoginLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsernameLabel.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        UsernameLabel.setForeground(new java.awt.Color(0, 0, 102));
        UsernameLabel.setText("Username");
        getContentPane().add(UsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 218, -1));

        PwdLabel.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        PwdLabel.setForeground(new java.awt.Color(0, 0, 102));
        PwdLabel.setText("Password");
        getContentPane().add(PwdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, 218, -1));

        UsernameField.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        UsernameField.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(UsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 360, 411, -1));

        PwdField.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        PwdField.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(PwdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 480, 411, -1));

        BackBtn.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        BackBtn.setForeground(new java.awt.Color(0, 51, 102));
        BackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1650, 100, -1, -1));

        LoginBtn.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        LoginBtn.setForeground(new java.awt.Color(0, 0, 102));
        LoginBtn.setText("Login");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 650, -1, -1));

        ViewCompDetBtn.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        ViewCompDetBtn.setForeground(new java.awt.Color(0, 0, 102));
        ViewCompDetBtn.setText("View Complaint Details");
        ViewCompDetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewCompDetBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ViewCompDetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 850, -1, -1));

        LoginLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Admin Login.png"))); // NOI18N
        LoginLabel.setText("Label");
        getContentPane().add(LoginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here:
        if(UsernameField.getText().equals("admin") && PwdField.getText().equals("admin") )
        {
            JOptionPane.showMessageDialog(null,"Logged in successfully!");
        }
        else
            JOptionPane.showMessageDialog(null,"Incorrect Username or Password!");
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void ViewCompDetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewCompDetBtnActionPerformed
        // TODO add your handling code here:
        new ViewComplaintDetails().setVisible(true);
    }//GEN-LAST:event_ViewCompDetBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        this.toBack();
	MainPage newFrame1 = new MainPage();
	newFrame1.setVisible(true);
	newFrame1.toFront();
    }//GEN-LAST:event_BackBtnActionPerformed
    
    /*private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        //int a = JOptionPane.showConfirmDialog(null,"Do you want to exit?","Select",JOptionPane.YES_NO_OPTION);
        System.exit(0);
    }*/ 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JPasswordField PwdField;
    private javax.swing.JLabel PwdLabel;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JButton ViewCompDetBtn;
    // End of variables declaration//GEN-END:variables
}
