/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package drrm;

/**
 *
 * @author harsh
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regComplaint = new javax.swing.JButton();
        DisProne = new javax.swing.JButton();
        checkStatus = new javax.swing.JButton();
        adminlabel = new javax.swing.JLabel();
        Admin = new javax.swing.JButton();
        MainPageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regComplaint.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        regComplaint.setForeground(new java.awt.Color(0, 0, 102));
        regComplaint.setText("Register Complaint");
        regComplaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regComplaintActionPerformed(evt);
            }
        });
        getContentPane().add(regComplaint, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 486, -1));

        DisProne.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        DisProne.setForeground(new java.awt.Color(0, 0, 102));
        DisProne.setText("Disaster Prone Zones ");
        DisProne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisProneActionPerformed(evt);
            }
        });
        getContentPane().add(DisProne, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 650, 486, -1));

        checkStatus.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        checkStatus.setForeground(new java.awt.Color(0, 0, 102));
        checkStatus.setText("Check Complaint Status");
        checkStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkStatusActionPerformed(evt);
            }
        });
        getContentPane().add(checkStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 830, -1, -1));

        adminlabel.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        adminlabel.setForeground(new java.awt.Color(255, 255, 255));
        adminlabel.setText("Admin Login");
        getContentPane().add(adminlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 660, -1, -1));

        Admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/adminlogin.png"))); // NOI18N
        Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminActionPerformed(evt);
            }
        });
        getContentPane().add(Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 450, -1, -1));

        MainPageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Disaster Risk and Redressal.jpg"))); // NOI18N
        MainPageLabel.setText("Label");
        getContentPane().add(MainPageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regComplaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regComplaintActionPerformed
        // TODO add your handling code here:
        new RegComplaint().setVisible(true);
    }//GEN-LAST:event_regComplaintActionPerformed

    private void DisProneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisProneActionPerformed
        // TODO add your handling code here:
        new DisasterProne().setVisible(true);
    }//GEN-LAST:event_DisProneActionPerformed

    private void checkStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkStatusActionPerformed
        // TODO add your handling code here:
        new CheckStatus().setVisible(true);
    }//GEN-LAST:event_checkStatusActionPerformed

    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
    }//GEN-LAST:event_AdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin;
    private javax.swing.JButton DisProne;
    private javax.swing.JLabel MainPageLabel;
    private javax.swing.JLabel adminlabel;
    private javax.swing.JButton checkStatus;
    private javax.swing.JButton regComplaint;
    // End of variables declaration//GEN-END:variables
}
