/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package drrm;

import dao.ConnectionProvider;
import dao.DbOperations;
import dao.RegCompDao;
import drrm.RegComplaint;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.RegCompModel;
/**
 *
 * @author harsh
 */
public class RegComplaint extends javax.swing.JFrame {

    /**
     * Creates new form RegComplaint
     */
    String imagePth = null;
    ImageIcon imageicon = new ImageIcon(imagePth);
    public RegComplaint() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameLabel = new javax.swing.JLabel();
        PhoneLabel = new javax.swing.JLabel();
        StateRCLabel = new javax.swing.JLabel();
        PlaceIncLabel = new javax.swing.JLabel();
        DisasterLabel = new javax.swing.JLabel();
        ComplaintLabel = new javax.swing.JLabel();
        PostLabel = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        UploadBtn = new javax.swing.JButton();
        SubmitBtn = new javax.swing.JButton();
        NameField = new javax.swing.JTextField();
        PhoneField = new javax.swing.JTextField();
        StateField = new javax.swing.JTextField();
        PlaceField = new javax.swing.JTextField();
        DisComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        CompTextArea = new javax.swing.JTextArea();
        PicProofLabel = new javax.swing.JLabel();
        DateField = new javax.swing.JTextField();
        CidLabel = new javax.swing.JLabel();
        CidField = new javax.swing.JTextField();
        BackBtn = new javax.swing.JButton();
        RegCompLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameLabel.setFont(new java.awt.Font("Georgia", 1, 28)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(255, 255, 255));
        NameLabel.setText("Name");
        getContentPane().add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 253, -1));

        PhoneLabel.setFont(new java.awt.Font("Georgia", 1, 28)); // NOI18N
        PhoneLabel.setForeground(new java.awt.Color(255, 255, 255));
        PhoneLabel.setText("Phone Number");
        getContentPane().add(PhoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 253, -1));

        StateRCLabel.setFont(new java.awt.Font("Georgia", 1, 28)); // NOI18N
        StateRCLabel.setForeground(new java.awt.Color(255, 255, 255));
        StateRCLabel.setText("State");
        getContentPane().add(StateRCLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 253, -1));

        PlaceIncLabel.setFont(new java.awt.Font("Georgia", 1, 28)); // NOI18N
        PlaceIncLabel.setForeground(new java.awt.Color(255, 255, 255));
        PlaceIncLabel.setText("Place of Incident");
        getContentPane().add(PlaceIncLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, 253, -1));

        DisasterLabel.setFont(new java.awt.Font("Georgia", 1, 28)); // NOI18N
        DisasterLabel.setForeground(new java.awt.Color(255, 255, 255));
        DisasterLabel.setText("Disaster");
        getContentPane().add(DisasterLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 590, 253, -1));

        ComplaintLabel.setFont(new java.awt.Font("Georgia", 1, 28)); // NOI18N
        ComplaintLabel.setForeground(new java.awt.Color(255, 255, 255));
        ComplaintLabel.setText("Complaint");
        getContentPane().add(ComplaintLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 690, 253, -1));

        PostLabel.setFont(new java.awt.Font("Georgia", 1, 28)); // NOI18N
        PostLabel.setForeground(new java.awt.Color(255, 255, 255));
        PostLabel.setText("Picture Proof");
        getContentPane().add(PostLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 890, 253, -1));

        DateLabel.setFont(new java.awt.Font("Georgia", 1, 28)); // NOI18N
        DateLabel.setForeground(new java.awt.Color(255, 255, 255));
        DateLabel.setText("Date");
        getContentPane().add(DateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 830, -1, -1));

        UploadBtn.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        UploadBtn.setForeground(new java.awt.Color(0, 0, 102));
        UploadBtn.setText("Upload");
        UploadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadBtnActionPerformed(evt);
            }
        });
        getContentPane().add(UploadBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 960, -1, -1));

        SubmitBtn.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        SubmitBtn.setForeground(new java.awt.Color(0, 0, 102));
        SubmitBtn.setText("SUBMIT");
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SubmitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 950, -1, -1));

        NameField.setFont(new java.awt.Font("Georgia", 1, 26)); // NOI18N
        NameField.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(NameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 490, -1));

        PhoneField.setFont(new java.awt.Font("Georgia", 1, 26)); // NOI18N
        PhoneField.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(PhoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 490, -1));

        StateField.setFont(new java.awt.Font("Georgia", 1, 26)); // NOI18N
        StateField.setForeground(new java.awt.Color(0, 51, 102));
        StateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StateFieldActionPerformed(evt);
            }
        });
        getContentPane().add(StateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 490, -1));

        PlaceField.setFont(new java.awt.Font("Georgia", 1, 26)); // NOI18N
        PlaceField.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(PlaceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 530, 490, -1));

        DisComboBox.setFont(new java.awt.Font("Georgia", 1, 26)); // NOI18N
        DisComboBox.setForeground(new java.awt.Color(0, 51, 102));
        DisComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Flood", "Earthquake", "Tsunami", "Drought", "Landslide", "Cyclone", "Volcanic Erruption", "Wildfire", " " }));
        DisComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(DisComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 590, 490, -1));

        CompTextArea.setColumns(20);
        CompTextArea.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        CompTextArea.setRows(5);
        jScrollPane1.setViewportView(CompTextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 670, 490, 150));

        PicProofLabel.setForeground(new java.awt.Color(255, 255, 255));
        PicProofLabel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                PicProofLabelComponentShown(evt);
            }
        });
        getContentPane().add(PicProofLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 850, 490, 170));

        DateField.setFont(new java.awt.Font("Georgia", 1, 26)); // NOI18N
        DateField.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(DateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 830, 254, -1));

        CidLabel.setFont(new java.awt.Font("Georgia", 1, 28)); // NOI18N
        CidLabel.setForeground(new java.awt.Color(255, 255, 255));
        CidLabel.setText("CID");
        getContentPane().add(CidLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, -1));

        CidField.setFont(new java.awt.Font("Georgia", 1, 26)); // NOI18N
        CidField.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(CidField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 490, -1));

        BackBtn.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        BackBtn.setForeground(new java.awt.Color(0, 51, 102));
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1610, 110, -1, -1));

        RegCompLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Register Complaint.png"))); // NOI18N
        RegCompLabel.setText("Label");
        getContentPane().add(RegCompLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StateFieldActionPerformed

    private void DisComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisComboBoxActionPerformed

    private void UploadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadBtnActionPerformed
        // TODO add your handling code here:
        /*JFileChooser filec = new JFileChooser();
		filec.setCurrentDirectory(new File(System.getProperty("user.home")));

		FileNameExtensionFilter fileFilter = new FileNameExtensionFilter("*.Images","jpg","png","gif");
		filec.addChoosableFileFilter(fileFilter);
		int fileState = filec.showSaveDialog(null);
		if(fileState == JFileChooser.APPROVE_OPTION)
		{
			File selectedFile = filec.getSelectedFile();
			String path = selectedFile.getAbsolutePath();
                        imagePth = path;
			PicProofLabel.setIcon(new ImageIcon(path));
			PicProofLabel.setIcon(resizePic(path));
		}
		else if(fileState == JFileChooser.CANCEL_OPTION)
		{
			System.out.println("No Image Selected");
		}*/
        
        JFileChooser jfile = new JFileChooser();

	jfile.setCurrentDirectory (new File (System.getProperty("user.home")));

	FileNameExtensionFilter filter = new FileNameExtensionFilter("Image", "jpg","png");

	jfile.addChoosableFileFilter(filter);

	int result = jfile.showSaveDialog (null);

	File selectedFile = jfile.getSelectedFile();

	String filename = selectedFile.getName();

	if (filename.endsWith(".jpg")||filename.endsWith(".JPG")||filename.endsWith("PNG")||filename.endsWith(".png")||filename.endsWith(".jpeg")) {
		if (result == JFileChooser. APPROVE_OPTION) {
			String path = selectedFile.getAbsolutePath();

			ImageIcon myImage = new ImageIcon(path);

			Image img = myImage.getImage();

			Image newImage = img.getScaledInstance (PicProofLabel.getWidth(), PicProofLabel.getHeight(), Image. SCALE_SMOOTH);

			ImageIcon image = new ImageIcon(newImage); 
			PicProofLabel.setIcon(image);
			FileInputStream fis= null;

			try{

				Connection con = ConnectionProvider.getCon();

				fis = new FileInputStream (path);

				PreparedStatement pat;
                                pat = con.prepareStatement ("INSERT INTO complaint (picture) values (?)");

				pat.setBinaryStream(1, fis);

				int response = JOptionPane.showConfirmDialog(rootPane, "Are You Sure To Save Image", "Confirm", JOptionPane. YES_NO_OPTION);

				if (response == 0) {

					int record = pat.executeUpdate();

					if (record == 1) {

						JOptionPane.showMessageDialog(rootPane, "Data is stored..", "Ok Done", 1);

					}else{

						JOptionPane.showMessageDialog(rootPane, "Sorry.","Can't Store Image", 1);

					}
				}
				if (response == 1) {

					JOptionPane.showMessageDialog (rootPane, "Cancelled By User..", "Cancel..",1);
				}
			}catch (Exception ex) {
				System.out.println(""+ex);
			}
                }
    }//GEN-LAST:event_UploadBtnActionPerformed
}
    private void PicProofLabelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PicProofLabelComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_PicProofLabelComponentShown

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        // TODO add your handling code here:
        //Connection con = ConnectionProvider.getCon();
        //Statement st =  con.createStatement();
        //ResultSet rs=st.executeQuery("select * from display where state='"+state+"';");
        try{
            RegCompModel reg =new RegCompModel();
            reg.setCid(CidField.getText());
            reg.setName (NameField.getText());
            reg.setPhonenumber(PhoneField.getText());
            reg.setState(StateField.getText());
            reg.setPlaceofincident(PlaceField.getText());
            reg.setDisastername(DisComboBox.getSelectedItem().toString());
            reg.setComplaint(CompTextArea.getText());
            reg.setDate(DateField.getText());
            //FileInputStream img = new FileInputStream(new File(imagePth));
            //img.setBinaryStream();
            //reg.setPicproof();
            //reg.setPicproof(PicProofLabel.getAccessibleContext());
            
            RegCompDao.submit(reg);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Enter all fields");
            setVisible(false);
        }
    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        this.toBack();
	MainPage newFrame1 = new MainPage();
	newFrame1.setVisible(true);
	newFrame1.toFront();
    }//GEN-LAST:event_BackBtnActionPerformed

    public ImageIcon resizePic(String picPath)
    {
	ImageIcon myImg = new ImageIcon(picPath);
	Image img = myImg.getImage().getScaledInstance(PicProofLabel.getWidth(), PicProofLabel.getHeight(), Image.SCALE_SMOOTH);
	ImageIcon myPicture = new ImageIcon(img);
	return myPicture;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegComplaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegComplaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegComplaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegComplaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegComplaint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JTextField CidField;
    private javax.swing.JLabel CidLabel;
    private javax.swing.JTextArea CompTextArea;
    private javax.swing.JLabel ComplaintLabel;
    private javax.swing.JTextField DateField;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JComboBox<String> DisComboBox;
    private javax.swing.JLabel DisasterLabel;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField PhoneField;
    private javax.swing.JLabel PhoneLabel;
    private javax.swing.JLabel PicProofLabel;
    private javax.swing.JTextField PlaceField;
    private javax.swing.JLabel PlaceIncLabel;
    private javax.swing.JLabel PostLabel;
    private javax.swing.JLabel RegCompLabel;
    private javax.swing.JTextField StateField;
    private javax.swing.JLabel StateRCLabel;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JButton UploadBtn;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
