/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package drrm;

import dao.ConnectionProvider;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author harsh
 */
public class ViewComplaintDetails extends javax.swing.JFrame {

    /**
     * Creates new form ViewComplaintDetails
     */
    public ViewComplaintDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DateCompLabel = new javax.swing.JLabel();
        StateCompLabel = new javax.swing.JLabel();
        DateCompField = new javax.swing.JTextField();
        StateCompField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ViewTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        AssRespForBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        EnterBtn = new javax.swing.JButton();
        ViewComp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DateCompLabel.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        DateCompLabel.setForeground(new java.awt.Color(255, 255, 255));
        DateCompLabel.setText("Date");
        getContentPane().add(DateCompLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        StateCompLabel.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        StateCompLabel.setForeground(new java.awt.Color(255, 255, 255));
        StateCompLabel.setText("State");
        getContentPane().add(StateCompLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, -1, -1));

        DateCompField.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        DateCompField.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(DateCompField, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, 420, -1));

        StateCompField.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        StateCompField.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(StateCompField, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 420, -1));

        ViewTable.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        ViewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CID", "Name", "Phone Number", "Complaint", "Place of incident", "Picture of Proof"
            }
        ));
        jScrollPane1.setViewportView(ViewTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 482, 1719, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("View Complaint Details");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(681, 60, -1, -1));

        AssRespForBtn.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        AssRespForBtn.setForeground(new java.awt.Color(0, 51, 102));
        AssRespForBtn.setText("Assign Response Force");
        AssRespForBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssRespForBtnActionPerformed(evt);
            }
        });
        getContentPane().add(AssRespForBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 260, -1, -1));

        BackBtn.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        BackBtn.setForeground(new java.awt.Color(0, 51, 102));
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1690, 90, -1, -1));

        EnterBtn.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        EnterBtn.setForeground(new java.awt.Color(0, 51, 102));
        EnterBtn.setText("Enter");
        EnterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterBtnActionPerformed(evt);
            }
        });
        getContentPane().add(EnterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 408, -1, -1));

        ViewComp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/View Complaint Details.png"))); // NOI18N
        ViewComp.setText("Label");
        getContentPane().add(ViewComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AssRespForBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssRespForBtnActionPerformed
        // TODO add your handling code here:
        new AssignResponseForce().setVisible(true);
    }//GEN-LAST:event_AssRespForBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        this.toBack();
	Login newFrame2 = new Login();
	newFrame2.setVisible(true);
	newFrame2.toFront();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void EnterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterBtnActionPerformed
        // TODO add your handling code here:
        String date=DateCompField.getText();
        String state=StateCompField.getText();
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st =  con.createStatement();
            ResultSet rs=st.executeQuery("select * from complaint where date_inc='"+date+"' and state='"+state+"';");
            ViewTable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"No record exists!");
            setVisible(false);
        }
    }//GEN-LAST:event_EnterBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewComplaintDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewComplaintDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewComplaintDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewComplaintDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewComplaintDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssRespForBtn;
    private javax.swing.JButton BackBtn;
    private javax.swing.JTextField DateCompField;
    private javax.swing.JLabel DateCompLabel;
    private javax.swing.JButton EnterBtn;
    private javax.swing.JTextField StateCompField;
    private javax.swing.JLabel StateCompLabel;
    private javax.swing.JLabel ViewComp;
    private javax.swing.JTable ViewTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
